### ISSUE TITLE
weakdh.py crashes on non-FQDN in weakdh.hosts

### ISSUE THREAD

**Issue by sanderjo** [cudeso/tools#1]
weakdh.py crashes on non-FQDN in weakdh.hosts, like an empty line and a non resolvale name

```
$ cat weakdh.hosts 
www.google.be
sslreader.eweka.nl
bla

www.xs4all.nl
```

results in (with some logging put into weaddh.py by me):

```
$ python weakdh.py 
host is www.google.be

url is  https://weakdh.org/check/?server=www.google.be
host is sslreader.eweka.nl

url is  https://weakdh.org/check/?server=sslreader.eweka.nl
host is bla

url is  https://weakdh.org/check/?server=bla
Traceback (most recent call last):
  File "weakdh.py", line 34, in <module>
    ip = json_data["ip_addresses"][0]
TypeError: 'NoneType' object has no attribute '__getitem__'

```

and

```
$ python weakdh.py 
host is www.google.be

url is  https://weakdh.org/check/?server=www.google.be
host is sslreader.eweka.nl

url is  https://weakdh.org/check/?server=sslreader.eweka.nl
host is 

url is  https://weakdh.org/check/?server=
Traceback (most recent call last):
  File "weakdh.py", line 30, in <module>
    response = urllib2.urlopen( base_url + host )
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request

```

Possible solution: try/except

**Comment by cudeso** [comment]
Fixed in [https://github.com/cudeso/tools/commit/3c6dc572e3fe61cb2dec3167a78413d62bc4d80b]
